version: "3.8"

services:
  app_blue:
    image: "${BLUE_IMAGE}"
    container_name: app_blue
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    ports:
      - "${BLUE_HOST_PORT}:${PORT}"
    restart: unless-stopped

  app_green:
    image: "${GREEN_IMAGE}"
    container_name: app_green
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    ports:
      - "${GREEN_HOST_PORT}:${PORT}"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - app_blue
      - app_green
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - BLUE_SERVICE_HOST=app_blue
      - GREEN_SERVICE_HOST=app_green
      - APP_PORT=${PORT}
    volumes:
      - nginx_logs:/var/log/nginx
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    command: >
      sh -c "
        mkdir -p /var/log/nginx &&
        touch /var/log/nginx/access.log /var/log/nginx/error.log &&
        chmod 644 /var/log/nginx/*.log &&
        if [ \"$$ACTIVE_POOL\" = 'green' ]; then
          export PRIMARY_HOST=$$GREEN_SERVICE_HOST;
          export BACKUP_HOST=$$BLUE_SERVICE_HOST;
        else
          export PRIMARY_HOST=$$BLUE_SERVICE_HOST;
          export BACKUP_HOST=$$GREEN_SERVICE_HOST;
        fi &&
        cat /etc/nginx/nginx.conf.template | 
        sed 's|\\\$${PRIMARY_HOST}|'\"$$PRIMARY_HOST\"'|g' |
        sed 's|\\\$${BACKUP_HOST}|'\"$$BACKUP_HOST\"'|g' |
        sed 's|\\\$${APP_PORT}|'\"$$APP_PORT\"'|g' |
        sed 's|\\\$${ACTIVE_POOL}|'\"$$ACTIVE_POOL\"'|g' > /etc/nginx/nginx.conf &&
        echo '=== Generated nginx.conf ===' &&
        cat /etc/nginx/nginx.conf &&
        echo '=== Starting nginx ===' &&
        nginx -g 'daemon off;'
      "
    restart: unless-stopped

  alert_watcher:
    build: ./alert_watcher
    container_name: alert_watcher
    depends_on:
      - nginx
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD}
      - WINDOW_SIZE=${WINDOW_SIZE}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC}
      - MAINTENANCE_MODE=${MAINTENANCE_MODE}
      - INITIAL_ACTIVE_POOL=${ACTIVE_POOL}
    volumes:
      - nginx_logs:/var/log/nginx:ro
    restart: unless-stopped

volumes:
  nginx_logs:
